### ISSUE TITLE
Hash sharding scale strategy question

### ISSUE THREAD

**Issue by abv76** [chrislusf/vasto#10]
Using consistent hash for sharding will take more time to migrate between shards，and range key queries would be hard to implement.
Would you consider key range sharding for another sharding strategy？

**Comment by chrislusf** [comment]
Why consistent hashing will take more time?

**Comment by abv76** [comment]
Comparing to iterate then filtrate all the keys within rocksdb，using rocksdb file to migrate shards seems more efficient？
Would you consider other sharding strategy like hash & range such as mangoDB use?   https://docs.mongodb.com/manual/core/sharding-shard-key/
Besides，do you accept any PR for some features enhancement？ @chrislusf
