### ISSUE TITLE
Question: why client <> store communication uses plain TCP instead of GRPC?

### ISSUE THREAD

**Issue by lming** [chrislusf/vasto#12]
Could you share the design rationale? Thanks!

**Comment by chrislusf** [comment]
Faster. grpc has non trivial performance cost.

**Comment by lming** [comment]
I assume each TCP connection can only have one pending request. So the size of the conn poll determines the number of concurrent requests on the fly, right?

**Comment by chrislusf** [comment]
There could be asynchronous requests

**Comment by lming** [comment]
Thanks for answering!
