### ISSUE TITLE
vasto vs cassandra

### ISSUE THREAD

**Issue by YumcoderCom** [chrislusf/vasto#13]
@chrislusf 
I would be obliged if you could compare between vasto and cassandra
-- why Vasto will be needed when we can run Cassandra with RocksDB (as engine)

**Comment by chrislusf** [comment]
1. Cassandra can not iterate all rows. There are token range via CQL, but it has heavy impact on performance.
2. Vasto wants to be programmatically elastic. It could be physically spread to X machines, or merge into a couple of machines.
3. Vasto is for more latency-sensitive work load. It tries to ensure physically isolated and dedicated servers for a portion of data. There are no cross-talk during actual querying time.
