### ISSUE TITLE
./go.test.sh error 

### ISSUE THREAD

**Issue by abv76** [chrislusf/vasto#5]
OS:ubuntu; gcc version 7.3.0; go 1.10.4; and rocksdb master branch with shared lib: librocksdb.so.5.17
after export LD_LIBRARY_PATH=/usr/local/lib, the go.test.sh is running now,
but still fail for the below message:

ok      github.com/chrislusf/vasto/storage/binlog       0.097s  coverage: 82.4% of statements
ok      github.com/chrislusf/vasto/storage/codec        0.027s  coverage: 94.4% of statements
free(): invalid pointer
FAIL    github.com/chrislusf/vasto/storage/rocks        0.083s

**Comment by chrislusf** [comment]
No clue for your env. Please follow steps in here

https://github.com/chrislusf/vasto/blob/master/.travis.yml
