### ISSUE TITLE
vasto start server or store fail

### ISSUE THREAD

**Issue by abv76** [chrislusf/vasto#6]
go.test.sh run successful now.
when start vasto sever or store，I encounter below errors：

E1013 00:06:29.768819    8411 store_in_cluster.go:30] read file /tmp/go-build169079065/cluster.config: open /tmp/go-build169079065/cluster.config: no such file or directory

does it need certrain cluster.config files？

**Comment by chrislusf** [comment]
It is ok to ignore this. Will change it to warning instead.
