### ISSUE TITLE
vasto bench fail

### ISSUE THREAD

**Issue by abv76** [chrislusf/vasto#7]
I tried to use the vasto bench to test it. first open one terminal for vasto master or server，then open the other for vasto bench，but vasto bench always showed as below and won't make any progress again：

benchmarking on cluster with master localhost:8278
put :    --- [--------------------------------------------------------------------]   0% NaN ops/sec

The vasto master or server side just printed out the message such as：
I1013 10:05:21.397870    8502 master_server.go:41] Vasto master starts on :8278
I1013 10:05:30.134602    8502 master_grpc_server_for_client.go:30] + client 127.0.0.1:54859
E1013 10:05:30.135152    8502 master_grpc_server_for_client.go:96] master add client benchmarker: client key is already in use: benchmark:dc1:127.0.0.1:54859
I1013 10:05:30.135119    8502 master_grpc_server_for_client.go:30] + client 127.0.0.1:54861
E1013 10:05:30.152217    8502 master_grpc_server_for_client.go:96] master add client benchmarker: client key is already in use: benchmark:dc1:127.0.0.1:54861
I1013 10:06:31.644583    8502 master_grpc_server_for_client.go:41] - client 127.0.0.1:54859
I1013 10:06:31.645002    8502 master_grpc_server_for_client.go:41] - client 127.0.0.1:54861
I1013 10:06:39.134168    8502 master_grpc_server_for_client.go:30] + client 127.0.0.1:54864
E1013 10:06:39.134886    8502 master_grpc_server_for_client.go:96] master add client benchmarker: client key is already in use: benchmark:dc1:127.0.0.1:54864
I1013 10:06:53.839102    8502 master_grpc_server_for_client.go:41] - client 127.0.0.1:54864

I tried to use vasto bench -c1 parameter， but it did not change anything for the bench result.
Is there any settings I miss？ In my knowledge, vasto server include both vasto store and master, so it should be fine to open a vasto server for vasto bench to test.
I just want to make a benchmark test about the vasto performance，could you provide detail instructions to benchmark vasto ？

**Comment by chrislusf** [comment]
Here are steps https://github.com/chrislusf/vasto/wiki/Get-Started
