### ISSUE TITLE
some wiki guard mistake，benchmark result. possibilities of other KV engine replacement？

### ISSUE THREAD

**Issue by abv76** [chrislusf/vasto#8]
// start one vasto shell
vasto shell
  create cluster ks1 dc1 3 1
  use keyspace ks1
  desc ks1 dc1
  

> delete cluster ks1 dc1

**the last line should be delete**

I get my bechmark on a i7 7550/16G laptop
time ./vasto bench --keyspace=ks1 -n 1024000 -c 16
benchmarking on cluster with master localhost:8278
put :    35s [===================================================================>] 100% 29145.12 ops/sec
put,get    :   29058.5 op/s
Microseconds per op:
Count: 1024000  Average: 527.6445  StdDev: 371.17
Min: 0.0000  Median: 464.7338  Max: 26443.0000
put :    35s [====================================================================] 100% 29142.38 ops/sec
get :    31s [===================================================================>] 100% 32221.78 ops/sec
put,get    :   32110.0 op/s
Microseconds per op:
Count: 1024000  Average: 470.7078  StdDev: 201.14
Min: 0.0000  Median: 464.2912  Max: 15578.0000
put :    35s [====================================================================] 100% 29142.38 ops/sec
get :    31s [====================================================================] 100% 32218.41 ops/sec
real    1m7.219s
user    0m43.063s
sys     1m17.438s

By the way，is it possible to replace the embed rocksdb with other KV engine？ 
For most of other KY engines，there is no equivalent Merge operation as Roscksdb‘s. Only some simple put/get/delete/iterate/batch write operations

**Comment by abv76** [comment]
Many other KV engines provide iterate operation too, as well as get/put/write operations, but most don't implement merge operation.
Of course，all those engines have their own APIs, which are not compatible with rocksdb’s. 
Do you mean that to replace the beneath KV engines, most of the vasto KV related API must be change to satisfied vasto and KV inter operation?

**Comment by chrislusf** [comment]
What are the KV engines you have in mind?

**Comment by chrislusf** [comment]
maybe later.
